### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [jhennies/amst#4]
Dear @jhennies ,

first of all thanks for putting out this resource! I'm working on a collaborative project where we were thinking of reusing the code you published here in a larger scenario. In order to re-use the code, it would be great if you could put a license file in the repository so that we know under which constraints we are allowed to reuse the code. 

If you're not sure which license is the right one (permissive versus restrictive licensing), I'm happy to assist. Also check out 

https://choosealicense.com/

Thanks!

Best,
Robert

**Comment by jhennies** [comment]
Done for both repos, thanks for the request!
